POST http://localhost:3000/api/user/update
Content-Type: application/json

{
    "email": "Tengo4cafeteras@gmail.com"
}

### anashe

GET http://localhost:3000/api/event/myevents/94462f61-4614-4c47-b004-337387b42bc0



### create new Event

POST http://localhost:3000/api/event/create
Content-Type: application/json

{
    "husbandName": "Camilo",
    "wifeName": "Leticia",
    "location": "Cancun",
    "eventDate": "2025-11-11T00:00:00.000Z",
    "itinerary": "Casamiento, fiestita, morfamos y vayanse todos a la verga",
    "dressCode": "Formal",
    "kidsAllowed": false,
    "specialMenu": true

}

### update event 

PATCH http://localhost:3000/api/event/edit/94462f61-4614-4c47-b004-337387b42bc0
Content-Type: application/json

{
    "wifeName": "Leticia",
    "location": "Irlanda"
}

### get all events from user 

GET http://localhost:3000/api/event/myevents
